FROM ubuntu:22.04

WORKDIR /app

ARG SPRING_VERSION=1.0.3
ARG CDT_VERSION=4.1.0

RUN case $(uname -m) in \
        x86_64 | amd64) \
            arch=amd64;; \
        aarch64 | arm64) \
            arch=arm64;; \
        *) echo "Unkown architecture" && exit 1;; \
    esac \
    && apt-get update \
    && apt install -y --no-install-recommends python3 python3-pip \
    && wget https://github.com/huangyangcong/eos-build/blob/main/packages/spring_${SPRING_VERSION}_${arch}.deb \
    && dpkg -i spring_${SPRING_VERSION}_${arch}.deb \
    && rm spring_${SPRING_VERSION}_${arch}.deb \
    && wget https://github.com/huangyangcong/eos-build/blob/main/packages/cdt_${CDT_VERSION}_${arch}.deb \
    && dpkg -i cdt_${CDT_VERSION}_${arch}.deb \
    && rm cdt_${CDT_VERSION}_${arch}.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install pygments
USER root
EXPOSE 8888
