name: build eos

on:
  push:
    branches: ["main"]
    tags: ["*"]
    paths:
      - '.github/workflows/build.yml' 
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/build.yml'

env:
  CDT_VERSION: "v4.1.0"
  SPRING_VERSION: "v1.0.3"
  CONTRACT_VERSION: "v3.6.0"
  LLVM_VERSION: "17"
  
jobs:
  build-cdt:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install dependencies
        run: |
          brew update
          # brew tap huangyangcong/llvm
          brew install llvm@${{ env.LLVM_VERSION }} opam ocaml libxml2 ninja gcc@11 automake libtool boost doxygen pyenv binutils zlib bzip2
          brew link llvm@${{ env.LLVM_VERSION }}
          
      - name: Clone cdt
        run: |
          git clone -b release/4.1 --single-branch https://github.com/AntelopeIO/cdt.git

      - name: Build cdt
        run: |
          cd cdt
          echo "cdt_DIR=$(pwd)/build/lib/cmake/cdt" >> $GITHUB_ENV
          echo "cdt_BUILD_DIR=$(pwd)/build" >> $GITHUB_ENV
          git checkout ${{ env.CDT_VERSION }}
          git pull origin ${{ env.CDT_VERSION }}
          git submodule update --init --recursive
          
          mkdir build
          cd build
          echo "BUILDING CDT FROM ${{ env.CDT_VERSION }}"
          cmake  -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm@${{ env.LLVM_VERSION }}/bin/clang-${{ env.LLVM_VERSION }} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@${{ env.LLVM_VERSION }}/bin/clang++ ..
          echo "FINISHED CMAKE CDT"
          make -j $(sysctl -n hw.ncpu)
          echo "FINISHED MAKE CDT FROM ${{ env.CDT_VERSION }}"
          echo "FINISHED INSTALL CDT FROM ${{ env.CDT_VERSION }}"
          #cd packages
          #chmod -R +x .
          #./generate_package.sh brew mac-cdt-${{ env.CDT_VERSION }} arm64
          echo "FINISHED GENERATE PACKAGE CDT"
          sudo make install
          
      # - name: Always Save cdt
      #   id: cache-cdt-save
      #   if: always()
      #   uses: actions/cache/save@v4
      #   with:
      #     key: eos-cdt-${{ runner.os }}-cmake
      #     path: |
      #       cdt/build
      #       cdt/libraries

      - name: Clone spring
        run: |
          git clone -b release/1.0 --single-branch https://github.com/AntelopeIO/spring.git

      - name: Build spring
        run: |
          cd spring
          echo "spring_DIR=$(pwd)/spring_build/lib/cmake/spring" >> $GITHUB_ENV
          echo "spring_BUILD_DIR=$(pwd)/spring_build" >> $GITHUB_ENV
          git checkout ${{ env.SPRING_VERSION }}
          git pull origin ${{ env.SPRING_VERSION }}
          git submodule update --init --recursive

          mkdir -p spring_build/packages
          cd spring_build
          echo "BUILDING SPRING FROM ${{ env.SPRING_VERSION }}"
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm@${{ env.LLVM_VERSION }}/bin/clang-${{ env.LLVM_VERSION }} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@${{ env.LLVM_VERSION }}/bin/clang++ -DCMAKE_PREFIX_PATH="/opt/homebrew/opt/llvm@${{ env.LLVM_VERSION }};/opt/homebrew/opt/gcc@11" ../
          echo "FINISHED CMAKE SPRING"
          make -j $(sysctl -n hw.ncpu) package
          echo "FINISHED BUILDING SPRING"
          sudo make install
          
      # - name: Always Save spring
      #   id: cache-spring-save
      #   if: always()
      #   uses: actions/cache/save@v4
      #   with:
      #     key: eos-spring-${{ runner.os }}-cmake
      #     path: |
      #         spring/spring_build
      #         spring/libraries
          
      - name: Clone & build eosio-time
        run: |
          git clone https://github.com/eosnetworkfoundation/eosio.time.git
          cd eosio.time
          echo "export eosio_time_DIR=$(pwd)" >> $GITHUB_ENV
          cdt-cpp eosio.time.cpp
           
      - name: Clone & build eos-system-contract
        run: |
          git clone https://github.com/eosnetworkfoundation/eos-system-contracts.git
          cd eos-system-contracts
          git checkout ${{ env.CONTRACT_VERSION }}
          git pull origin ${{ env.CONTRACT_VERSION }}
          echo 'export eos_system_contracts_DIR=$(pwd)' >> $GITHUB_ENV
          git checkout ${{ env.CONTRACT_VERSION }}
          git pull origin ${{ env.CONTRACT_VERSION }}
          echo "BUILDING eos-system-contract FROM ${{ env.CONTRACT_VERSION }}"
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -Dspring_DIR=${{ env.spring_DIR }} ..
          make -j $(sysctl -n hw.ncpu)
          echo "FINISH eos-system-contract FROM ${{ env.CONTRACT_VERSION }}"

      - name: Copy output
        run: |
          mkdir -p output
          mkdir -p output/eosio.time
          mkdir -p output/eos-system-contracts
          mkdir -p output/spring
          mkdir -p output/cdt
          mv ${{ env.spring_BUILD_DIR }}/* output/spring
          mv ${{ env.cdt_BUILD_DIR }}/* output/cdt
          mv ${{ env.eosio_time_DIR }}/* output/eosio.time
          mv ${{ env.eos_system_contracts_DIR }}/build/contracts/* output/eos-system-contracts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-artifacts
          path: output/*
